// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

function unauthorizedError() returns ErrorUnauthorized => {
    body: {code: 401, message: "Not signed in"}
};

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todos
    #
    # + return - returns can be any of following types
    # http:Ok (Matching todos)
    # http:Unauthorized (Not signed in)
    resource function get me/todos(http:RequestContext ctx, int 'limit = 20, int offset = 0) returns TodoList|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return unauthorizedError();
        }
        return listTodosForCaller(caller.userId, 'limit, offset);
    }

    # Change one of the caller's todos to done or not-done
    #
    # + return - returns can be any of following types
    # http:Ok (Todo updated)
    # http:NotFound (No such todo for the caller)
    # http:Unauthorized (Not signed in)
    resource function patch me/todos/[string todoId](http:RequestContext ctx, @http:Payload TodoUpdate payload) returns Todo|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return unauthorizedError();
        }
        Todo? updated = check updateTodoForCaller(caller.userId, todoId, payload.done);
        if updated is () {
            return <ErrorNotFound>{body: {code: 404, message: "No such todo for the caller"}};
        }
        return updated;
    }

    # Add a new todo for the caller
    #
    # + return - returns can be any of following types
    # http:Created (Todo created)
    # http:BadRequest (Invalid todo)
    # http:Unauthorized (Not signed in)
    resource function post me/todos(http:RequestContext ctx, @http:Payload NewTodo payload) returns Todo|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return unauthorizedError();
        }
        string title = payload.title.trim();
        if title == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "title must not be empty"}};
        }
        Todo created = check createTodoForCaller(caller.userId, title);
        return created;
    }
}

public type Todo record {
    string id;
    string title;
    boolean done;
    string createdAt;
};

public type NewTodo record {
    string title;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoUpdate record {
    boolean done;
};

public type TodoList record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
